### ISSUE TITLE
Proposal to manage a standalone fork of MrTroot/autofish

### ISSUE THREAD

**Issue by myl7** [Wudji/XPlus-AutoFish#1]
While MrTroot/autofish is outdated, I notice that your fork is the most active one that can adapt to the latest Minecraft version.
I would like to ask if you can merge several other pending PRs in the upstream (e.g., MrTroot/autofish#46 MrTroot/autofish#53) to setup a standalone fork, to host further development of the autofish mod and gather the community that needs the mod?

I am the maintainer of [myl7/autofish].
If you are willing to gather the community, I would abandon my fork and redirect users to your fork.
I would also help some trivial stuff if you want me.

[myl7/autofish]: https://github.com/myl7/autofish

**Comment by Wudji** [comment]
Thank you for your advice. I have just merged the changes from https://github.com/MrTroot/autofish/pull/46 and https://github.com/MrTroot/autofish/pull/53 and created a new branch `1.19.4`

感谢你的建议，我刚刚将https://github.com/MrTroot/autofish/pull/46 和 https://github.com/MrTroot/autofish/pull/53 的更改合并了，并创建了一个新的分支`1.19.4`。
