### ISSUE TITLE
Request to add features

### ISSUE THREAD

**Issue by ghost** [Wudji/XPlus-AutoFish#12]
When a fish bites the float, reel in the fishing rod too fast.
The server manager is suspicious of me.
Can you create an option to adjust the speed at which you pull the fishing rod when a fish bites the float?

**Comment by ghost** [comment]
I also hope they add this feature in version 1.20.1!

**Comment by Wudji** [comment]
Add in `v1.2.0` for Minecraft 1.19.4 1.20.1 1.20.6 1.21
