### ISSUE TITLE
1.21默认浮标检测无法使用，只能使用声音检测

### ISSUE THREAD

**Issue by SerendipityR-2022** [Wudji/XPlus-AutoFish#13]
如题，安装模组后默认配置下，钓上鱼并不会触发收杆，也没有开放水域检测提示
游戏版本：1.21 (Farbic 0.15.11)
模组版本：1.10

**Comment by Wudji** [comment]
mojang闲的难受把EntityVelocityUpdateS2CPacket的数量级改了
已在v1.1.1中修复
https://modrinth.com/mod/x+-autofish/version/1.1.1-fabric-1.21

**Comment by SerendipityR-2022** [comment]
谢谢，现在可以正常工作
