### ISSUE TITLE
[Feature Request] Add configurable auto eat option

### ISSUE THREAD

**Issue by Art0sh** [Wudji/XPlus-AutoFish#17]
What the title says.
I would like to have an option/function that automatically eats (maybe if something is in offhand?) if hunger falls below a set level.
I wanted to request that, since a server I play on has a safeguard against afk fishing, where you have to stay above a set hunger level to be allowed to fish (And lose some hunger with every fish caught)

**Comment by Wudji** [comment]
Thank you for your suggestions, but this function is way too cheat...
