### ISSUE TITLE
CTD during initialization "this.autofish" is null [MC-1.21 neoforge-21.1.21]

### ISSUE THREAD

**Issue by Slaymeister** [Wudji/XPlus-AutoFish#22]
Edit: Modpack reference removed. Specific conflicting mod added.

Full Mod List:
XPlus Autofish 1.3.1
Cloth Config API 15.0.130
Placebo-1.21.1-9.4.1 (Note: this is a popular library mod with 173M downloads on Curseforge. You do not need to install any other mods to repro the issue.)  https://www.curseforge.com/minecraft/mc-mods/placebo

Also tested with neoforge 21.1.23 (current) and got the same error

Error:
The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "com.wudji.xplusautofish.XPlusAutofish.tick(net.minecraft.client.Minecraft)" because "this.autofish" is null

Crash Report:
Crash report with minimal mods: https://pastebin.com/S1PrLJ5A

Repro:
In Curseforge, install a new instance of Minecraft 1.21 with Neoforge 21.1.21+. Add XPlus Autofish, Cloth API, and Placebo. Launch instance.  Crash will occur before main menu.

**Comment by Slaymeister** [comment]
https://github.com/Shadows-of-Fire/Placebo/issues/89

**Comment by Wudji** [comment]
Since they think this mod is a cheat mod, I don't have any interest in fixing compat with it.

**Comment by Slaymeister** [comment]
They said that, but I think they also put in a fix in their latest version. I just tested it and it now works.

**Comment by Slaymeister** [comment]
Built version 1.3.2 and verified fix. Thank you!
