### ISSUE TITLE
1.21 fabric 1.3.0启用持续模式后误判收竿

### ISSUE THREAD

**Issue by GhostMillet2024** [Wudji/XPlus-AutoFish#24]
`1.3.0` 持续模式下即使没有鱼上钩也可能自动收竿, 关闭持续模式后正常
单人和服务器都有这个问题, `1.2.0` 没有, 可能是bug?
> mods:
**XPlus AutoFish**
[Simple Voice Chat](https://www.mcmod.cn/class/3693.html)
[Cloth Config API](https://www.mcmod.cn/class/2346.html)
[Fabric API](https://www.mcmod.cn/class/3124.html)

```
{
  "isAutofishEnabled": true,
  "multiRod": false,
  "isOpenWaterDetectEnabled": true,
  "noBreak": true,
  "persistentMode": true,
  "useSoundDetection": true,
  "forceMPDetection": false,
  "recastDelay": 500,
  "randomPercent": 0,
  "reelInDelay": 1,
  "clearLagRegex": "\\[ClearLag\\] Removed [0-9]+ Entities!"
}
```

**Comment by dodo939** [comment]
是的，我也是有这个情况，版本1.3.1 fabric
