### ISSUE TITLE
使用FreeCamera时无法自动钓鱼

### ISSUE THREAD

**Issue by Trcmoe** [Wudji/XPlus-AutoFish#26]
# 问题描述
钓鱼的时候，启用Tweakeroo的FreeCamera后自动钓鱼会失效。
视频描述：https://www.bilibili.com/video/av113101101859079/
# 模组
https://mclo.gs/aIVD5OE#L267

**Comment by Wudji** [comment]
tweakeroo有一个选项可以允许玩家在使用灵魂出窍后继续操作玩家本体，尝试打开那个选项进行钓鱼。

**Comment by Wudji** [comment]
![image](https://github.com/user-attachments/assets/8b1040b9-1586-4414-9060-03cb5e55d309)
