### ISSUE TITLE
[Bug] 在启用了持续模式后，即使启用了断裂保护，也会使用手持的1耐久鱼竿钓鱼

### ISSUE THREAD

**Issue by EatHatsuneShallots** [Wudji/XPlus-AutoFish#29]
Minecraft 版本：1.21.1 Fabric

XAutoFish 版本：1.3.3

服务器信息："Leaves" server

问题描述：在启用了持续模式后，开始自动钓鱼时仍会使用手持的 **1 耐久** 鱼竿钓鱼（即使启用了断裂保护）

补充说明：因为这个 Bug 把我满级鱼竿给霍霍没了

**Comment by Wudji** [comment]
fixed in the following versions:
- 1.21.x fabric
- 1.21.x neoforge
- 1.20.6 fabric 
- 1.20.1 fabric 
- 1.20.1 forge

**Comment by EatHatsuneShallots** [comment]
> fixed in the following versions:

损害值（Damage Value）貌似是硬编码的，如果服务端修改了鱼竿的最大耐久值，可能会出现问题
希望能改成动态获取

**Comment by Wudji** [comment]
> > fixed in the following versions:
> 
> 损害值（Damage Value）貌似是硬编码的，如果服务端修改了鱼竿的最大耐久值，可能会出现问题 希望能改成动态获取

再开个issue吧。。。等我回来有时间改
