### ISSUE TITLE
Break Protection Not Working

### ISSUE THREAD

**Issue by Dan-Mizu** [Wudji/XPlus-AutoFish#4]
I had Break Protection on and it still broke my fishing rod.

**Comment by Wudji** [comment]
Works fine for me (mod version 0.10.2, Fabric 1.20.4)
Could you give us some more specific details regarding this issue?

**Comment by Dan-Mizu** [comment]
MC 1.20.1 Fabric 0.15.3 v0.9.10

**Comment by Wudji** [comment]
However, it works fine for me.
