### ISSUE TITLE
Sound detection not working

### ISSUE THREAD

**Issue by SoupChugger** [Wudji/XPlus-AutoFish#5]
The sound detection isn't working for me - it doesn't detect when the bobber is hooked, as if theres no autofisher mod at all. 
The motion detection works fine for me but misses sometimes so I was trying the sound one.

**Comment by Wudji** [comment]
I tested the sound detection on the 1.20.1 paper server, and it seems to be functioning properly.
Could you please give us some more specific details about this problem?

**Comment by Cacti2432** [comment]
Same issue
