### ISSUE TITLE
Variable reel & recast

### ISSUE THREAD

**Issue by mrcao** [Wudji/XPlus-AutoFish#7]
I've been trying to edit the code but realised I have no idea how to compile it into the jar... but I wanted to add a variable reel & recast timing to circumvent some detectors. 

Could you perhaps add this or show me how to download and recompile the code adequately? I think my code by itself is fine I just don't know how the java compiling method works.

**Comment by Wudji** [comment]
Added in v1.0.0: https://github.com/Wudji/XPlus-AutoFish/commit/b9d7313101ef5d590802cfc96a354ee5c11515a5
