### ISSUE TITLE
Open Water Detection not working

### ISSUE THREAD

**Issue by Gamemassa** [Wudji/XPlus-AutoFish#9]
Hi, I'm on Fabric 1.20.4 and the Open Water Detection feature doesn't look like it's working (or I'm just doing it wrong).

**Comment by Wudji** [comment]
I tested the Open Water Detection feature in 1.20.4 on the local game and paper server, and it runs as intended.

[Open water detection will now only alert the user once if they are not fishing in open water.](https://github.com/Wudji/XPlus-AutoFish/commit/e7e9e8b6d2a573a096439e63177280794c4af435)
The gif below shows how it works:
https://suzxx-my.sharepoint.com/personal/qianhai_suzxx_onmicrosoft_com/_layouts/52/download.aspx?share=EYAKqtjDmfNKk1ZINNlrOpoBBcgh4sJ-5tWpmDq-wCAGuw

**Comment by Gamemassa** [comment]
> I tested the Open Water Detection feature in 1.20.4 on the local game and paper server, and it runs as intended.
> 
> [Open water detection will now only alert the user once if they are not fishing in open water.](https://github.com/Wudji/XPlus-AutoFish/commit/e7e9e8b6d2a573a096439e63177280794c4af435) The gif below shows how it works: https://suzxx-my.sharepoint.com/personal/qianhai_suzxx_onmicrosoft_com/_layouts/52/download.aspx?share=EYAKqtjDmfNKk1ZINNlrOpoBBcgh4sJ-5tWpmDq-wCAGuw

~~Ok, just to be clear, you said it should alert the user if they are **NOT** fishing in open water, but in the GIF the alert appears to pop up if you **ARE** fishing in open water, so I'm really confused now.~~ Oh, never mind, it notifies in both cases.

Please disregard. It's working now. Not sure why it wasn't before (maybe I just needed to restart my game after I enabled it). You can close this thread.
